spring.application.name=patientservice
spring.datasource.url = jdbc:postgresql://localhost:5432/patient-service
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto = update

spring.datasource.hikari.auto-commit=false

server.port=4000
logging.level.root=info